### ISSUE TITLE
hyperlinks in News Items text?

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-geonode#19]
Is there a format for creating hyperlinks in the text of a News Item?

**Comment by ischneider** [comment]
The format for content is textile: http://redcloth.org/hobix.com/textile/

I've added some help text and a link to this in the admin site (not deployed yet).

**Comment by jonpmarino** [comment]
ok. thanks.

**Comment by garnertb** [comment]
Looks resolved, closing.
